import os
import platform


def get_country_dict():
    return {
        "Afghanistan": "Afghanistan",
        "AK": "United States",
        "Alabama": "United States",
        "Alaska": "United States",
        "Alaska region": "United States",
        "Albania": "Albania",
        "Algeria": "Algeria",
        "American Samoa": "American Samoa",
        "Andorra": "Andorra",
        "Angola": "Angola",
        "Anguilla": "Anguilla",
        "Antarctica": "Antarctica",
        "Antigua and Barbuda": "Antigua and Barbuda",
        "AR": "United States",
        "Argentina": "Argentina",
        "Arizona": "United States",
        "Arkansas": "United States",
        "Armenia": "Armenia",
        "Aruba": "Aruba",
        "Australia": "Australia",
        "Australia region": "Australia",
        "Austria": "Austria",
        "AZ": "United States",
        "Azerbaijan": "Azerbaijan",
        "Azores": "Azores",
        "Bahamas": "Bahamas",
        "Bahrain": "Bahrain",
        "Bangladesh": "Bangladesh",
        "Barbados": "Barbados",
        "Belarus": "Belarus",
        "Belgium": "Belgium",
        "Belize": "Belize",
        "Benin": "Benin",
        "Bermuda": "Bermuda",
        "Bhutan": "Bhutan",
        "Bolivia": "Bolivia",
        "Bonaire": "Bonaire",
        "Bosnia and Herzegovina": "Bosnia and Herzegovina",
        "Botswana": "Botswana",
        "Bouvet Island": "Bouvet Island",
        "Brazil": "Brazil",
        "British Indian Ocean Territory": "British Indian Ocean Territory",
        "British Virgin Islands": "British Virgin Islands",
        "Brunei": "Brunei Darussalam",
        "Brunei Darussalam": "Brunei Darussalam",
        "Bulgaria": "Bulgaria",
        "Burkina Faso": "Burkina Faso",
        "Burundi": "Burundi",
        "CA": "United States",
        "Cabo Verde": "Cabo Verde",
        "Cambodia": "Cambodia",
        "Cameroon": "Cameroon",
        "California": "United States",
        "Canada": "Canada",
        "Canada region": "Canada",
        "Canarias": "Canarias",
        "Cayman Islands": "Cayman Islands",
        "Central African Republic": "Central African Republic",
        "Chad": "Chad",
        "Chile": "Chile",
        "China": "China",
        "Christmas Island": "Christmas Island",
        "CO": "United States",
        "Cocos Islands": "Cocos Islands",
        "Colombia": "Colombia",
        "Colorado": "United States",
        "Comoros": "Comoros",
        "Connecticut": "United States",
        "Cook Islands": "Cook Islands",
        "Costa Rica": "Costa Rica",
        "Côte d'Ivoire": "Côte d'Ivoire",
        "Croatia": "Croatia",
        "Cuba": "Cuba",
        "Curacao": "Curacao",
        "Cyprus": "Cyprus",
        "Czechia": "Czech Republic",
        "Delaware": "United States",
        "Democratic Republic of the Congo": "Congo DRC",
        "Denmark": "Denmark",
        "Djibouti": "Djibouti",
        "Dominica": "Dominica",
        "Dominican Republic": "Dominican Republic",
        "Ecuador": "Ecuador",
        "Ecuador region": "Ecuador",
        "Egypt": "Egypt",
        "El Salvador": "El Salvador",
        "Equatorial Guinea": "Equatorial Guinea",
        "Eritrea": "Eritrea",
        "Estonia": "Estonia",
        "Eswatini": "Eswatini",
        "Ethiopia": "Ethiopia",
        "Falkland Islands": "Falkland Islands",
        "Faroe Islands": "Faroe Islands",
        "Federated States of Micronesia": "Micronesia",
        "Florida": "United States",
        "Fiji": "Fiji",
        "Finland": "Finland",
        "France": "France",
        "French Guiana": "French Guiana",
        "French Polynesia": "French Polynesia",
        "French Polynesia region": "French Polynesia",
        "French Southern Territories": "French Southern Territories",
        "Gabon": "Gabon",
        "Gambia": "Gambia",
        "Georgia": "Georgia",
        "Germany": "Germany",
        "Ghana": "Ghana",
        "Gibraltar": "Gibraltar",
        "Glorioso Islands": "Glorioso Islands",
        "Greece": "Greece",
        "Greenland": "Greenland",
        "Grenada": "Grenada",
        "Guadeloupe": "Guadeloupe",
        "Guam": "Guam",
        "Guatemala": "Guatemala",
        "Guernsey": "Guernsey",
        "Guinea": "Guinea",
        "Guinea Bissau": "Guinea-Bissau",
        "Guinea-Bissau": "Guinea-Bissau",
        "Guyana": "Guyana",
        "Haiti": "Haiti",
        "Hawaii": "United States",
        "Heard Island and McDonald Islands": "Heard Island and McDonald Islands",
        "HI": "United States",
        "Honduras": "Honduras",
        "Hong Kong": "China",
        "Hungary": "Hungary",
        "Iceland": "Iceland",
        "ID": "United States",
        "Idaho": "United States",
        "Illinois": "United States",
        "India": "India",
        "India region": "India",
        "Indiana": "United States",
        "Indonesia": "Indonesia",
        "Iran": "Iran",
        "Iraq": "Iraq",
        "Ireland": "Ireland",
        "Isle of Man": "Isle of Man",
        "Israel": "Israel",
        "Italy": "Italy",
        "Jamaica": "Jamaica",
        "Japan": "Japan",
        "Japan Earthquake": "Japan",
        "Japan region": "Japan",
        "Jersey": "Jersey",
        "Jordan": "Jordan",
        "Juan De Nova Island": "Juan De Nova Island",
        "Kansas": "United States",
        "Kazakhstan": "Kazakhstan",
        "Kentucky": "United States",
        "Kenya": "Kenya",
        "Kiribati": "Kiribati",
        "Kiribati region": "Kiribati",
        "Kosovo": "Serbia",
        "KS": "United States",
        "Kuwait": "Kuwait",
        "KY": "United States",
        "Kyrgyzstan": "Kyrgyzstan",
        "Laos": "Laos",
        "Latvia": "Latvia",
        "Lebanon": "Lebanon",
        "Lesotho": "Lesotho",
        "Liberia": "Liberia",
        "Libya": "Libya",
        "Liechtenstein": "Liechtenstein",
        "Lithuania": "Lithuania",
        "Luxembourg": "Luxembourg",
        "Louisiana": "United States",
        "Madagascar": "Madagascar",
        "Madeira": "Madeira",
        "Maine": "United States",
        "Malawi": "Malawi",
        "Malaysia": "Malaysia",
        "Maldives": "Maldives",
        "Mali": "Mali",
        "Malta": "Malta",
        "Marshall Islands": "Marshall Islands",
        "Martinique": "Martinique",
        "Maryland": "United States",
        "Massachusetts": "United States",
        "Mauritania": "Mauritania",
        "Mauritius": "Mauritius",
        "Mayotte": "Mayotte",
        "Mexico": "Mexico",
        "Michigan": "United States",
        "Micronesia": "Micronesia",
        "Minnesota": "United States",
        "Mississippi": "United States",
        "Missouri": "United States",
        "MN": "United States",
        "MO": "United States",
        "Moldova": "Moldova",
        "Monaco": "Monaco",
        "Mongolia": "Mongolia",
        "Montana": "United States",
        "Montenegro": "Montenegro",
        "Montserrat": "Montserrat",
        "Morocco": "Morocco",
        "Mozambique": "Mozambique",
        "MT": "United States",
        "MX": "Mexico",
        "Myanmar": "Myanmar",
        "Namibia": "Namibia",
        "Nauru": "Nauru",
        "NC": "United States",
        "Nebraska": "United States",
        "Nepal": "Nepal",
        "Netherlands": "Netherlands",
        "Nevada": "United States",
        "New Caledonia": "New Caledonia",
        "New Hampshire": "United States",
        "New Jersey": "United States",
        "New Mexico": "United States",
        "New York": "United States",
        "New Zealand": "New Zealand",
        "New Zealand region": "New Zealand",
        "Nicaragua": "Nicaragua",
        "Niger": "Niger",
        "Nigeria": "Nigeria",
        "Niue": "Niue",
        "NJ": "United States",
        "NM": "United States",
        "Norfolk Island": "Norfolk Island",
        "North Carolina": "United States",
        "North Korea": "North Korea",
        "North Macedonia": "North Macedonia",
        "Northern Mariana Islands": "Northern Mariana Islands",
        "Norway": "Norway",
        "NV": "United States",
        "NY": "United States",
        "OK": "United States",
        "Oklahoma": "United States",
        "Ohio": "United States",
        "Oman": "Oman",
        "OR": "United States",
        "Oregon": "United States",
        "Pakistan": "Pakistan",
        "Palau": "Palau",
        "Palestine": "Palestinian Territory",
        "Palestinian Territory": "Palestinian Territory",
        "Panama": "Panama",
        "Papua New Guinea": "Papua New Guinea",
        "Paraguay": "Paraguay",
        "Pennsylvania": "United States",
        "Peru": "Peru",
        "Philippines": "Philippines",
        "Poland": "Poland",
        "Portugal": "Portugal",
        "Portugal region": "Portugal",
        "Puerto Rico": "Puerto Rico",
        "Qatar": "Qatar",
        "Republic of the Congo": "Congo",
        "Reunion": "Réunion",
        "Revilla Gigedo Islands": "Mexico",
        "Rhode Island": "Greece",
        "Romania": "Romania",
        "Russia": "Russian Federation",
        "Russia region": "Russian Federation",
        "Rwanda": "Rwanda",
        "Saint Barthelemy": "Saint Barthelemy",
        "Saint Eustatius and Saba": "Saint Eustatius",
        "Saint Helena": "Saint Helena",
        "Saint Kitts and Nevis": "Saint Kitts and Nevis",
        "Saint Lucia": "Saint Lucia",
        "Saint Martin": "Saint Martin",
        "Saint Pierre and Miquelon": "Saint Pierre and Miquelon",
        "Saint Vincent and the Grenadines": "Saint Vincent and the Grenadines",
        "Samoa": "Samoa",
        "San Marino": "San Marino",
        "Sao Tome and Principe": "Sao Tome and Principe",
        "Saudi Arabia": "Saudi Arabia",
        "Senegal": "Senegal",
        "Serbia": "Serbia",
        "Seychelles": "Seychelles",
        "Sierra Leone": "Sierra Leone",
        "Singapore": "Singapore",
        "Sint Maarten": "Sint Maarten",
        "Slovakia": "Slovakia",
        "Slovenia": "Slovenia",
        "Solomon Islands": "Solomon Islands",
        "Somalia": "Somalia",
        "South Africa": "South Africa",
        "South Georgia and South Sandwich Islands": "South Georgia and South Sandwich Islands",
        "South Carolina": "United States",
        "South Dakota": "United States",
        "South Korea": "South Korea",
        "South Sudan": "South Sudan",
        "Spain": "Spain",
        "Sri Lanka": "Sri Lanka",
        "Sudan": "Sudan",
        "Suriname": "Suriname",
        "Svalbard and Jan Mayen": "Svalbard",
        "Sweden": "Sweden",
        "Switzerland": "Switzerland",
        "Syria": "Syria",
        "Taiwan": "China",
        "Tajikistan": "Tajikistan",
        "Tanzania": "Tanzania",
        "Tennessee": "United States",
        "Texas": "United States",
        "Thailand": "Thailand",
        "Timor Leste": "Timor-Leste",
        "TN": "United States",
        "Togo": "Togo",
        "Tokelau": "Tokelau",
        "Tonga": "Tonga",
        "Trinidad and Tobago": "Trinidad and Tobago",
        "Tunisia": "Tunisia",
        "Turkey": "Turkiye",
        "Turkmenistan": "Turkmenistan",
        "Turks and Caicos Islands": "Turks and Caicos Islands",
        "Tuvalu": "Tuvalu",
        "TX": "United States",
        "U.S. Virgin Islands": "US Virgin Islands",
        "Uganda": "Uganda",
        "Ukraine": "Ukraine",
        "United Arab Emirates": "United Arab Emirates",
        "United Kingdom": "United Kingdom",
        "United States": "United States",
        "United States Minor Outlying Islands": "United States Minor Outlying Islands",
        "Uruguay": "Uruguay",
        "USA": "United States",
        "UT": "United States",
        "Utah": "United States",
        "Uzbekistan": "Uzbekistan",
        "Vanuatu": "Vanuatu",
        "Vatican City": "Vatican City",
        "Venezuela": "Venezuela",
        "Vermont": "United States",
        "Vietnam": "Vietnam",
        "Virginia": "United States",
        "WA": "United States",
        "Wallis and Futuna": "Wallis and Futuna",
        "Washington": "United States",
        "West Virginia": "United States",
        "Wisconsin": "United States",
        "WY": "United States",
        "Wyoming": "United States",
        "Yemen": "Yemen",
        "Zambia": "Zambia",
        "Zimbabwe": "Zimbabwe"
    }


def transform_country_name(s):
    return get_country_dict()[s] if s in get_country_dict().keys() else None


def print_saved_file_info(title, path):
    if "Windows" == platform.system():
        file_size = round(os.path.getsize(path) / 1024 / 1024, 2)
    else:
        file_size = round(os.path.getsize(path) / 1000 / 1000, 2)
    print(f"{title} stored in `{path}`, with the size: {file_size} MB.")
